QuestionsControllerのshowアクションを書き直した
sobaotto/honne_api pull request #4
Opened 2022-10-02 11:03 UTC by sobaotto

2022-10-04 11:05 UTC, graph226 requested changes

2022-10-04 11:05 UTC, graph226 commented on app/controllers/questions_controller.rb
> +    render json: { errors: { message: 'ページが見つかりません(アクセス権限なし)' } }, status: :not_found if @question.nil?
- アクセス権限がない場合は、404を返す ことは見ればわかる
- アクセス権限がない場合だけではなさそう

```suggestion
     render_not_found if @question.nil?
```

```
def render_not_found
  render json: { errors: { message: 'ページが見つかりません(アクセス権限なし)' } }, status: :not_found
```

2022-10-04 11:05 UTC, graph226 commented on app/models/question.rb
> +  def own_question?(user)
👍

2022-10-10 10:27 UTC, sobaotto commented on app/controllers/questions_controller.rb
> +    user = target_user
他のプルリクで、同じ質問してます。

2022-10-10 10:27 UTC, sobaotto commented on app/models/question.rb
> +    user_id == user.id
他のプルリクで、同じ質問してます。

2022-10-10 13:59 UTC, merged